[OPTION_WS420]
TITLE=WiseScan420_OCR Sample
COMMAND_TYPE=META
DEVICECHANGE=#GV0
TRACKCOUNT=2

[COMMAND_WS420]
#AA;Document Scan
#AD;Cancel Scan
#AR;Device reset
#GC;GetImage config.
#GV0;Version Info + Serial
#GV1;Version Info
#GSX;Get Sensor info
#GP17;Get Device Parameter
#GN0;Power On Count
#GN1;Scan Count
#GG;Micr Data
#GB0;Load Color Image
#GB1;Load IR Image
#GD;Check Online status
#SP17,0;Set device parameter
#SCB32,D200;Set Image Config.