[OCR]
;LOL=YES
TARGET=IDNAMEKORNODATE,IDNO,DRVNO,IDNAMEKOR,IDDATE,DRVDATE,DRVNAMEKOR,OSD,MRZ
;TARGET=DRVNAMEKORnoDRVno,IDNAMEKORNODATE,IDNO,DRVNO,IDNAMEKOR,IDDATE

OCR_ENABLE=YES
OCR_ENGINE=TESSERACT(libtesseract-5.dll)
OCR_GAMMA=1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 0.85, 0.7, 0.55
OCR_CH=RED, BLUE, GREEN, IR
OCR_RETRY_MAX=0
OCR_AFTERSCAN=YES
DESKEW=YES
;TIMEOUT=1500
JUMINNO_SAMPLE=123456-1234567,480101-1234567

[SCAN]
DUPLEX=NO
WIDTH=540
HEIGHT=1280
BPP=24
RESOLUTION=200
LIGHTSOURCE=RED
DPI=300
SCANSPEED=NO

[OSD]
LANG=OSD

[MRZ]
;LANG=OCRB
LANG=MRZF
FORMAT=1A,44A,44A
RECTANGLE=0.01W,0.75H,0.99W,0.9H
;BUSYBACKGROUND=0.5
;FONTHEIGHT_inMM=2.7
DESKEW=1.8
TIMEOUT=0
ROTATE=
SAVEDEBUGIMAGE=D
PATTERN=

[TRAVELDOC]
LANG=OCRB
RECTANGLE=0.01W,0.60H,0.99W,0.99H
;RECTANGLE=550,390,2000,454 ;front name
;RECTANGLE=30,780,2000,1220
BUSYBACKGROUND=0
ALLOWSPACE=YES
ALLOWNEWLINE=YES
FONTHEIGHT_inMM=
MINIMUM_CHAR_COUNT=30
;SAVEDEBUGIMAGE=YES
PATTERN=

[IDNO]
LANG=eng+jmc
;RECTANGLE=0.01W,0.40H,0.6W,0.5H
;RECTANGLE=20,250,600,320
BUSYBACKGROUND=0
GAMMA=1.8
DESKEW=0
TIMEOUT=0
PATTERN=\d\d\d\d\d\d-\d\d\d\d\d\d\d
SAVEDEBUGIMAGE=
FONTHEIGHT_inMM=
TryOCRinUnknownCARDTYPE=

[DRVNO]
LANG=jmc
;RECTANGLE=0.01W,0.40H,0.6W,0.5H
RECTANGLE=20,250,600,320
BUSYBACKGROUND=0
DESKEW=0
GAMMA=2.1
TIMEOUT=0
PATTERN=\d\d\d\d\d\d-\d\d\d\d\d\d\d
SAVEDEBUGIMAGE=
FONTHEIGHT_inMM=
TryOCRinUnknownCARDTYPE=

[IDDATE]
;LANG=jmd+~ENG
;LANG=jmd+kor+eng
LANG=JMD+ENG
;LANG=JMD
DESKEW=0.3
GAMMA=1.8
;RECTANGLE=0.2W,0.74H,0.76W,0.85H
RECTANGLE=0.2W,0.74H,0.76W,0.848H
PATTERN=\d\d\d\d. \d\*. \d\*.
BUSYBACKGROUND=1
SAVEDEBUGIMAGE=
FONTHEIGHT_inMM=
;OSDONLY=YES

[DRVDATE]
LANG=eng
;DESKEW=0.3
GAMMA=2.0
RECTANGLE=0.368W,0.84H,0.56W,0.98H
;RECTANGLE=0.33W,0.84H,0.56W,0.98H
PATTERN=\d\d\d\d. \d\*. \d\*.
BUSYBACKGROUND=10
SAVEDEBUGIMAGE=
FONTHEIGHT_inMM=
;OSDONLY=YES

[IDNAMEKOR]
LANG=KOR+~ENG
;RECTANGLE=0.1W,0.24H,0.6W,0.39H
RECTANGLE=0.07W,0.24H,0.6W,0.39H
;RECTANGLE=20,180,600,320
DESKEW=
GAMMA=1.9
BUSYBACKGROUND=NO
SAVEDEBUGIMAGE=
FONTHEIGHT_inMM=
;FONTHEIGHT_inMM=1.149
;OSDONLY=YES

[DRVNAMEKOR]
LANG=KOR+~ENG
;RECTANGLE=0.375W,0.26H,0.75W,0.36H
;RECTANGLE=0.37W,0.26H,0.75W,0.36H
RECTANGLE=0.37W,0.26H,0.75W,0.35H
;RECTANGLE=20,180,600,320
DESKEW=
GAMMA=1.92
BUSYBACKGROUND=0
SAVEDEBUGIMAGE=
FONTHEIGHT_inMM=
;FONTHEIGHT_inMM=1.149
;OSDONLY=YES

[ADDR]
LANG=KOR
RECTANGLE=0.1W,0.24H,0.6W,0.39H
;RECTANGLE=20,180,600,320
DESKEW=
GAMMA=1.0
ADDITIONALINFO=/
BUSYBACKGROUND=NO
SAVEDEBUGIMAGE=
FONTHEIGHT_inMM=
;FONTHEIGHT_inMM=1.149
;OSDONLY=YES

[IDNODATE]
LANG=jmc+jmd+eng
RECTANGLE=0.01W,0.40H,0.66W,0.99H

[IDNAMEKORNO]
LANG=ENG+KOR
;RECTANGLE=0.01W,0.26H,0.6W,0.5H
;RECTANGLE=20,180,600,320
BUSYBACKGROUND=1
SAVEDEBUGIMAGE=
PATTERN=K2~7\nD6-D7\nD6~8
FONTHEIGHT_inMM=
SEPERATOR=/

[IDNAMEKORNODATE]
LANG=ENG+KOR
;RECTANGLE=0.0571W,0.235H,0.7231W,0.9235H
;RECTANGLE=20,180,600,320
;FORMAT=2K+,6D-7D,1S,6A
FORMAT=2K+,6D-6D1C,1S
BUSYBACKGROUND=1
SAVEDEBUGIMAGE=
FONTHEIGHT_inMM=
SEPERATOR=/


[DRVCODE]
LANG=ENG+KDC
;RECTANGLE=510,298,672,338
RECTANGLE=71,37,85,43
FORMAT=6A
BUSYBACKGROUND=
SAVEDEBUGIMAGE=
FONTHEIGHT_inMM=

;3S='2D-2D-6D-2D' OR '2K 2D-6D-2D'
;4S='성 명:' OR 'N1N2N3'
[DRVNAMEKORnoDRVno]
LANG=ENG+KOR+jmc
;RECTANGLE=0.3612W,0.1297H,0.9921W,0.43H
RECTANGLE=0.3612W,0.128H,0.9921W,0.8H
;FORMAT=2K 2D-6D-2D,2K+,6D-7D
FORMAT=2L~2D~6D~2D,4S,6D-6D1C
OUTPUT=120
BUSYBACKGROUND=1
RGB_CHANNEL=5
SAVEDEBUGIMAGE=
SEPERATOR=/
DESKEW=

[DRVNAMEKORnoDRVnoCODE]
CONTAINER=DRVNAMEKORnoDRVno,DRVDATE,IDNO,DRVNO
SEPERATOR=/


[IDNOANALYSE]
OUTPUT=IDNO\nIDNAMEKOR\nIDDATE

[E13B]
LANG=mcr
RECTANGLE=0.01W,0.78H,0.99W,0.99H
PATTERN=\d\d\d\d\d\d-\d\d\d\d\d\d\d

[KOOKA]
LANG=KOR+ENG
;RECTANGLE=0.535W,0.24H,0.88W,0.86H
RECTANGLE=0.535W,0.25H,0.88W,0.86H
FORMAT=2K+,6D-6D1C,2D-6D+
SEPERATOR=/
BUSYBACKGROUND=9
SAVEDEBUGIMAGE=
RGB_CHANNEL=5
GAMMA=

[KOOKA2023]
LANG=KOR+ENG
RECTANGLE=0.3762W,0.1672H,0.8821W,0.4750H
FORMAT=2K+,6D-6D1C,2D-6D
SEPERATOR=/
BUSYBACKGROUND=0
SAVEDEBUGIMAGE=
RGB_CHANNEL=5
GAMMA=3

[BOKJI-CASHCD]
LANG=KOR+ENG
RECTANGLE=0.0157W,0.1406H,0.6493W,0.2172H
;FORMAT=2K+,2D.2D.2D,2S
FORMAT=2K+,3S,2S
SEPERATOR=/
BUSYBACKGROUND=
SAVEDEBUGIMAGE=
RGB_CHANNEL=5
GAMMA=

[BOKJI]
CONTAINER=BOKJI-NAMEJUNOCLASS,BOKJI-DATE
FORMAT=
SEPERATOR=/

[BOKJI2]
LANG=KOR
RECTANGLE=0.1083W,0.26H,0.67W,0.95H
FORMAT=2K+,6D-6D1C,2S,1S
OUTPUT=0132
BUSYBACKGROUND=
RGB_CHANNEL=5
SAVEDEBUGIMAGE=
SEPERATOR=/

[BOKJI-DATE]
LANG=ENG
;RECTANGLE=0.4134W,0.7H,0.6644W,0.8H
;RECTANGLE=0.4134W,0.75H,0.67W,0.85H
RECTANGLE=0.40W,0.75H,0.67W,0.95H
BUSYBACKGROUND=10
RGB_CHANNEL=5
SAVEDEBUGIMAGE=
FORMAT=1S

[BOKJI-NAMEJUNOCLASS]
;LANG=KOR+ENG
LANG=KOR
;RECTANGLE=0.1083W,0.26H,0.45W,0.527H
RECTANGLE=0.1083W,0.26H,0.45W,0.54H
FORMAT=2K+,6D-6D1C,2S
BUSYBACKGROUND=
RGB_CHANNEL=5
SAVEDEBUGIMAGE=
SEPERATOR=/

[OTHER]
LANG=eng

[OPTION]
IRIMAGE=YES

;FORMAT, D(DIGIT), K(KOREAN), S(SPECIAL, 1(DATE 4DIGIT YEAR), 2(DISABLE CLASS), 3(DATE 2DIGIT YEAR), 4(DRIV NAME: "성명:"), 5(DRVLICENSE NO: "충남 "), 
