[OPTION]
;LOGGING=YES
;LOG_API=YES
;LOG_MRP=YES
;LOG_OCR=YES
;LOG_SVC=YES
SLEEP=200

MODEL=PassPort Scanner
VID = 1C51
PID = 1300
;PID = 1301
VID2 = 1C51
PID2 = 1203

;AUTOSTART=FILEIMAGE
DPI_VALID=200,300,400,600,1200
;DPI_VALID=100,200,240,300,400,500,600
;DPI_VALID_SHADE=1200,600,300,200
DPI_VALID_SHADE=600,300,200

DESKEW=NO
;ROTATE=90
ROTATE=270
;CHECKSLIP=NO
;LOCAL_CERT=NO
;LOCAL_CERT_ANAL=NO
;LOCAL_CERT_GRAPH=160
;FILTER_CERT=0xFFFF00FF 0xFFFF00FF 0xFFFF00FF
;PLAY_SONG=C2D2C2

IRIMAGE=YES
RFDATA_AFTERSCAN=NO

SAVE_OCRFAIL=YES
MRZTOSERIAL_AFTERSCAN=YES
MAGNETIC_DATA=NO
BARCODE_DATA=NO

INTERVAL_INSECOND=0
DUPLEX_ATTACHEDVERTICAL=NO
OPENPAINTER_RIGHTBUTTON=YES

;SAVE_IMAGE_DEBUG=c:\top.jpg, c:\btm.jpg
;SAVE_IMAGE_DEBUG=c:\top.bmp, c:\btm.bmp
SAVEIMAGE=NO
SAVEIMAGEDIR=img

SHADING=YES
SHADEONHOST=YES
SHADERESTORE=YES
SHADEPICKUP=YES
SHADEBLACK_LEDON=NO
;SHADEBASE=shade(LLLLSSSS)_BRGB.bin
;SHADEBASE=shade(10060011)_BRGB.bin
SHADERESTORE_DISCON=NO

;GAMMA linked channel(ex. 2.2) independent channel(ex. 2.2 2.1 2.3) CURVE(ex. curve.bmp(bpp24 color))
;GAMMA_TOP=1.80
;GAMMA_TOP=1.7 1.8 1.9
;GAMMA_TOP=G:\Projects\IS\TTA-CERT\isw\curve\curve_ids300.bmp
;GAMMA_BTM=1.8 1.8 1.8

GAMMA_TOPOFFSET=0
GAMMA_BTMOFFSET=0

WIDTH_COLORFIXED=1200,600, 300, 200
WIDTH_GRAYFIXED=1200,600,300,200
;HEIGHT_COLORFIXED=400, 300, 200, 150
HEIGHT_COLORFIXED=1200, 600, 300, 200
HEIGHT_GRAYFIXED=1200,600,300,200

;cis
CIS_GAP_MM=0.0
;CIS_COLUMN=657

;MIN_LED_LEVEL = 10
;MIN_LED_LEVEL = 60
;SATURATION_LEVEL=0x80
;SATURATION_LEVEL=0xC0
;SATURATION_LEVEL=0xC8
;SATURATION_LEVEL=0xE8
;SATURATION_LEVEL=0xFF

;YR
MAX_TRY_CNT = 60;
MAX_CIS_WIDTH = 54
MAX_LED_LEVEL = 70
MIN_LED_LEVEL = 10
SATURATION_LEVEL=0xC0

;YT
;MAX_CIS_WIDTH = 216
;MAX_LED_LEVEL = 108

;CANON, VGAIN(255)
;MAX_CIS_WIDTH = 55
;MAX_LED_LEVEL = 80

;ATII
;MAX_CIS_WIDTH = 55
;MAX_LED_LEVEL = 160

;FOR C4R108(50.CISTYPE:10), FC4R108(50.CISTYPE:11)
;MAX_CIS_WIDTH = 108
;MAX_LED_LEVEL = 80

; FOR M206-A6M
;MAX_CIS_WIDTH = 92
;MAX_LED_LEVEL = 80

; FOR CM109-CF600
;MAX_CIS_WIDTH = 150
;MAX_LED_LEVEL = 80

;ADDRESS_FUSING=0x40000
;ADDRESS_DUMP=0xd400000
;ADDRESS_DOWNLOAD=0xc200000
;ADDRESS_FUSESHADE=0x380000

ADDRESS_DOWNLOAD=0x28400000
ADDRESS_FUSING=0x14000000
ADDRESS_FUSESHADE=0x143E0000
ADDRESS_DUMP=0x28000000

;ADDRESS_FUSESHADE=0xf0000
ADDRESS_BITMAP=0x29600000

[RF]
;READER=ACS ACR1281U PICC Reader 0
;READER=ACS ACR1281U PICC Interface 0
;READER=ACS ACR1281 PICC Reader 0
;READER=ACS ACR1281 CL Reader PICC 0
READER=Duali DE-ABCM Contactless Reader 0
IMAGEPATH=c:\img

[OCR]
OCR_ENABLE=YES
OCR_AFTERSCAN=YES
OCR_DLL=..\OMNIOCR\OMNIOCR.DLL

[SCAN]
DUPLEX=NO
WIDTH=540
HEIGHT=860
BPP=24
DPI=300
LIGHTSOURCE=GREEN
SCANSPEED=NO
RESOLUTION=300

[MAINTAIN]
QC=ys_lqc.ini

[EMULATE_OCR_RESULT]
;RESULT0=length,0, 0x1000, 0, barcode_data
;RESULT1=length,2, 0, 0x10, mrz_first
;RESULT2=length,1, 0, 0x10, mrz_second
RESULT0=0x2C,2, 0, 0x10, POCHNDING<<JIN<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
RESULT1=0x2C,1, 0, 0x10, E116647902CHN8203106F2301158LGKB0IKK<<<<A992
